### ISSUE TITLE
Update npgw-api-specification for customerDetails.cardHolderName

### ISSUE THREAD

**Issue by YuliaMatusevich** [NPGW/npgw-api-specification#12]
The field should accept Latin alphabetic letters, diacritics and spaces between parts of a name.

**Comment by LukieNumbrSlevin** [comment]
Will be updated in future PR

```
            cardHolderName:
              type: string
              description: Card holder name.
              example: Hal Jordan
              minLength: 1
              maxLength: 150
              pattern: '^[\p{L}0-9 \_.,-:&]+$'
```
