### ISSUE TITLE
Update npgw-api-specification for 'amount'

### ISSUE THREAD

**Issue by ViktoriyaED** [NPGW/npgw-api-specification#9]
Add value for amount field:
minimum
maximum

**Comment by LukieNumbrSlevin** [comment]
Completed by @SergeiDemyanenko 

```
        amount:
          type: integer
          minimum: 1
          maximum: 9999999
          description: Transaction amount.
          example: 1999
```
